site_name: Technical Info
site_url: https://keepbot.github.io/docs/
site_description: Collection of Technical guides
site_author: Dmitry Ivanov

repo_url: https://keepbot.github.io/

theme: readthedocs
#theme: cinder

copyright: Copyright &copy; 2016 Dmitry Ivanov.

google_analytics: ['UA-80208201-1', 'keepbot.github.io']
