site_name: 'Technical Info'
site_url: 'https://d-k-ivanov.github.io/docs/'
site_description: 'Collection of Technical guides'
site_author: 'Dmitriy Ivanov'

repo_name: 'Main site'
repo_url: 'https://d-k-ivanov.github.io/'

theme:
  name: 'windmill'

# theme:
#   name: 'material'
#   palette:
#     primary: 'blue grey'
#     accent: 'cyan'

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  extra.article_nav_top: false
  article_nav_bottom: false
  social:
    - type: 'github'
      link: 'https://github.com/d-k-ivanov'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/dmitriy-ivanov-5b9275b3/'


google_analytics: ['UA-80208201-1', 'd-k-ivanov.github.io']

copyright: Copyright &copy; 2016-2020 Dmitriy Ivanov.
  <script type="text/javascript"> (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(40819844, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true }); </script> <noscript><div><img src="https://mc.yandex.ru/watch/40819844" style="position:absolute; left:-9999px;" alt="" /></div></noscript>


